[package]
name = "cloud-op"
version = "0.2.4"
authors = ["Yieazy <yuitta@163.com>"]
license = "Apache-2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0", features = ["derive"] }
prost = "0.11"
rand = "0.8"
hex = "0.4"
cita-database = "0.3"
cita-vm = "0.3"
cita-types = "0.1"
cita_trie = "3.0"
rlp = "0.5"
bincode = "1.3"
bloomchain = "0.2"
# slog unable to compile because the latest version: 0.4.16 modifies the interface, todo delete
log = "0.4"
fs_extra = "1.2"
serde = "1.0"
serde_derive = "1.0"

# crypto_sm
libsm = "0.5"
# crypto_eth
tiny-keccak = { version = "2.0", features = ["keccak"] }
# storage
storage_rocksdb = { git = "https://github.com/cita-cloud/storage_rocksdb", package = "storage", branch = "v6.6.2" }
# execute
executor_evm = { git = "https://github.com/cita-cloud/executor_evm", package = "executor", branch = "v6.6.2" }

cloud-util = { git = "https://github.com/cita-cloud/cloud-util", branch = "v0.6.0" }
cita_cloud_proto = { git = "https://github.com/cita-cloud/cita_cloud_proto", branch = "v6.6.2" }
status_code = { package = "cloud-code", git = "https://github.com/cita-cloud/status_code", branch = "v0.6.0" }
