apiVersion: batch/v1
kind: Job
metadata:
  name: backup-job
spec:
  backoffLimit: 0
  manualSelector: true
  selector:
    matchLabels:
      app: backup
  template:
    metadata:
      labels:
        app: backup
    spec:
      containers:
      - args:
        - echo 'backup start\n' && cloud-op backup -c ./config/config.toml -n ./source
          && mv ./source/backup/* ./backup && echo 'move done!'
        command:
        - /bin/sh
        - -c
        image: docker.io/jayanring/cloud-op:latest
        imagePullPolicy: IfNotPresent
        name: cloud-op-backup
        resources:
          limits:
            cpu: 2000m
            memory: 4196Mi
          requests:
            cpu: 1000m
            memory: 2048Mi
        volumeMounts:
        - mountPath: /backup
          name: cloud-op-backup
        - mountPath: /source
          name: datadir-sla-overlord-node5-0
        - mountPath: /config
          name: node-config
      restartPolicy: Never
      volumes:
      - name: cloud-op-backup
        persistentVolumeClaim:
          claimName: cloud-op-backup
      - name: datadir-sla-overlord-node5-0
        persistentVolumeClaim:
          claimName: datadir-sla-overlord-node5-0
      - configMap:
          name: sla-overlord-node5-config
        name: node-config
