apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cloud-op-backup
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: nas-client-provisioner
  volumeMode: Filesystem
